"use client";

import { useCurrentLocale } from "@/locales/client";

/**
 * Localizzazione del layer UI del framework (E2 DS_REFACTORING_V1_PLAN).
 *
 * Gemello di `components/layouts/form.localization.ts` (che copre le etichette
 * dei form generate dal registry): qui vivono TUTTE le stringhe statiche dei
 * componenti del framework (layouts, moduli app-level, wrapper) nelle 3 lingue.
 *
 * Regole:
 * - L'italiano è la lingua sorgente: il tipo `UIStrings` è derivato da `it`,
 *   quindi `en`/`es` non compilano se manca una chiave (completezza garantita).
 * - Interpolazione con segnaposto `{nome}` tramite `fmtUI()` (es. `{brand}`).
 * - Nei componenti si accede SOLO via `useUIStrings()` (reattivo al locale):
 *   vietato importare direttamente i dizionari o cablare testo nel markup.
 * - Il DebugWidget (strumento di sviluppo) è volutamente fuori scope.
 */

const it = {
  common: {
    save: "Salva",
    close: "Chiudi",
    cancel: "Annulla",
    search: "Cerca...",
    copyToClipboard: "Copia negli appunti",
    closeNotification: "Chiudi notifica",
    closeDetails: "Chiudi dettagli",
    user: "Utente",
    userMenu: "Menu utente",
    loading: "Caricamento in corso…",
    sessionSync: "Sincronizzazione sessione in corso…",
    showPassword: "Mostra password",
    hidePassword: "Nascondi password",
    capsLockOn: "Blocco maiuscole attivo",
  },
  validation: {
    number: "Deve essere un numero",
    email: "Email non valida",
    vat: "Partita IVA non valida",
    personalId: "Codice Fiscale non valido (16 caratteri)",
    sdi: "Codice SDI non valido (7 caratteri)",
    required: "Campo obbligatorio",
    min: "Minimo {n} caratteri",
    max: "Massimo {n} caratteri",
  },
  auth: {
    emailLabel: "Indirizzo Email",
    emailPlaceholder: "name@example.com",
    passwordLabel: "Password",
    passwordPlaceholder: "••••••••",
    rememberMe: "Ricordami",
    forgotPassword: "Dimenticato la password?",
    signIn: "Accedi",
    signingIn: "Accesso in corso…",
    noAccount: "Non hai ancora un account?",
    registerNow: "Registrati ora",
    backToLogin: "Torna al login / Esci",
    hasAccount: "Hai già un account?",
    loginHere: "Accedi qui",
    register: {
      typePersonal: "Privato",
      typeBusiness: "Azienda",
      typeGovernment: "P.A.",
      typeEducation: "Edu",
      name: "Nome Completo",
      fiscalCountry: "Nazione Fiscale (Residenza)",
      country: "Nazione",
      passwordStrength: "Forza password:",
      passwordTooShort: "Troppo corta",
      passwordWeak: "Debole",
      passwordMedium: "Media",
      passwordStrong: "Forte ✨",
      vatNumberPersonalIT: "Codice Fiscale (Opzionale)",
      vatNumberPersonalES: "DNI / NIE / NIF (Opzionale)",
      vatNumberPersonalGeneric: "Identificativo Fiscale / NIF (Opzionale)",
      vatNumberPersonalPlaceholderIT: "es. RSSMRA80A01H501U",
      vatNumberPersonalPlaceholderES: "es. 12345678A o Y1234567Z",
      vatNumberPersonalPlaceholderGeneric: "es. Identificativo Fiscale locale",
      residenceAddress: "Indirizzo di Residenza",
      addressPlaceholder: "Inizia a digitare l'indirizzo...",
      orgDetails: "Dettagli Organizzazione",
      vatNumberIT: "Partita IVA",
      vatNumberES: "NIF / CIF (Spagna)",
      vatNumberGeneric: "Partita IVA / Tax ID",
      viesValidated: "Convalidato tramite VIES Commissione Europea ✨",
      vatWarningInfo: "Informativa Fiscale (Direttiva 2006/112/CE): L'identificativo IVA inserito non risulta registrato o abilitato nel sistema VIES per le operazioni intracomunitarie. La registrazione è consentita, tuttavia le fatture saranno assoggettate all'aliquota IVA ordinaria stabilita nello Stato membro di stabilimento (VAT inclusive), escludendo l'inversione contabile (Reverse Charge).",
      viesOfflineWarning: "Il servizio di convalida VIES è temporaneamente offline. La registrazione è consentita, ma l'abilitazione al regime di esenzione IVA intracomunitaria verrà verificata successivamente.",
      companyNameBusiness: "Ragione Sociale Azienda",
      companyNameGovernment: "Denominazione Ente Pubblico",
      companyNameEducation: "Nome Istituto / Università",
      companyNamePlaceholderBusiness: "ACME S.r.l.",
      companyNamePlaceholderGovernment: "Ministero dell'Interno",
      companyNamePlaceholderEducation: "Università / Istituto Scolastico",
      legalAddress: "Indirizzo Sede Legale Ufficiale",
      sdiCode: "Codice Destinatario SDI (Opzionale)",
      sdiPlaceholder: "7 caratteri",
      officeCode: "Codice Ufficio PA (IPA) - Richiesto",
      officePlaceholder: "6 caratteri",
      cigCode: "Codice CIG (Opzionale)",
      cupCode: "Codice CUP (Opzionale)",
      acceptTerms: "Accetto la privacy policy e i termini di servizio.",
      acceptTermsPrefix: "Accetto la",
      privacyPolicy: "privacy policy",
      acceptTermsConj: "e i",
      termsOfService: "termini di servizio",
      acceptTermsSuffix: ".",
      register: "Registrati",
    },
    mfa: {
      title: "Autenticazione a Due Fattori",
      totpPrompt: "Inserisci il codice a 6 cifre generato da {factor}.",
      code: "Codice di verifica",
      submit: "Verifica codice",
      backupCta: "Hai perso il dispositivo? Usa un codice di backup",
      backupPrompt: "Inserisci uno dei codici di backup salvati quando hai configurato la 2FA. Reimposteremo il secondo fattore; poi accedi con la tua password.",
      backupSubmit: "Reimposta",
      backupCancel: "Annulla",
      trustDevice: "Fidati di questo dispositivo per 30 giorni",
    },
    reauth: {
      title: "Conferma la tua identità",
      passwordPrompt: "Per continuare con questa operazione sensibile, conferma la tua password.",
      mfaPrompt: "Inserisci il codice a 6 cifre generato da {factor} per continuare.",
      confirm: "Conferma",
      verifying: "Verifica in corso…",
    },
    mfaEnroll: {
      title: "Configura l'app di autenticazione",
      instructions: "Scansiona il codice QR con la tua app di autenticazione (Google Authenticator, 1Password…) oppure inserisci la chiave manualmente, poi conferma il primo codice generato.",
      scanHint: "Scansiona con l'app",
      manualKeyLabel: "Chiave manuale",
      openInApp: "Apri nell'app di autenticazione",
      copyKey: "Copia la chiave",
      confirm: "Conferma",
    },
    mfaBackup: {
      warning: "Conserva questi codici in un luogo sicuro: non verranno mostrati di nuovo. Ogni codice funziona una sola volta.",
      copy: "Copia",
      download: "Scarica .txt",
      done: "Fatto, li ho salvati",
    },
    reset: {
      title: "Reimposta Password",
      sendLink: "Invia link di reset",
      newPassword: "Nuova Password",
      confirmPassword: "Conferma Password",
      forLabel: "Per:",
    },
    verify: {
      title: "Verifica la tua Email",
      desc: "Abbiamo inviato un link di verifica all'indirizzo {email}. Controlla la tua casella di posta e fai clic sul link per attivare il tuo account.",
      button: "Ho verificato l'email (Aggiorna)",
      resendEmailButton: "Invia di nuovo l'email",
      resendCooldown: "Riinvia tra {n}s",
    },
  },
  layout: {
    errorTitle: "Si è verificato un errore",
    authCheck: "Verifica autenticazione...",
    secureRedirect: "Reindirizzamento sicuro al portale di autenticazione...",
    orgSetupTitle: "Setup Organizzazione",
    onboardingInProgress: "Onboarding dell'organizzazione in corso...",
    invalidServerData: "I dati ricevuti dal server non sono validi. Ricarica la pagina o contatta l'assistenza.",
    claimsAlignError: "Impossibile allineare l'organizzazione del profilo. Contatta l'assistenza.",
    skipToContent: "Salta al contenuto principale",
    mainNavAria: "Navigazione principale",
    footerNavAria: "Collegamenti a piè di pagina",
    rightsReserved: "Tutti i diritti riservati.",
    openMenu: "Apri il menu di navigazione",
    contentErrorTitle: "Qualcosa è andato storto",
    contentErrorBody: "Il contenuto non può essere mostrato. Riprova o ricarica la pagina.",
    retry: "Riprova",
    palette: {
      title: "Palette comandi",
      placeholder: "Vai al modulo…",
      noResults: "Nessun modulo trovato",
      hint: "naviga",
    },
    views: {
      empty: {
        title: "Niente da mostrare",
        description: "Non ci sono elementi da visualizzare qui.",
      },
      switcher: {
        list: "Vista elenco",
        kanban: "Vista kanban",
        gantt: "Vista Gantt",
      },
      kanban: {
        itemCount: "{n} elementi",
        columnEmpty: "Nessun elemento",
      },
      gantt: {
        week: "Settimana",
        month: "Mese",
        today: "Oggi",
        withoutDates: "{n} elementi senza date non mostrati",
      },
    },
  },
  sidebar: {
    collapse: "Collassa Sidebar",
    expand: "Espandi Sidebar",
    notifications: "Notifiche",
    messages: "Messaggi",
    serviceStatus: "Stato del Servizio",
    serviceStatusOk: "Stato Servizio: OK",
    changeTheme: "Cambia Tema",
    themeLabel: "Tema: {mode}",
    settings: "Impostazioni",
    support: "Supporto",
    openSupport: "Apri Supporto",
    aiAgent: "AI Agent",
    logout: "Esci",
    disconnect: "Disconnetti",
  },
  form: {
    noPermission: "Non si dispone dei permessi necessari per compilare questo modulo.",
    submitError: "Errore durante la sottomissione.",
  },
  filter: {
    activeFilters: "Filtri attivi:",
    removeAll: "Rimuovi tutti",
    removeFilter: "Rimuovi filtro {label}",
  },
  providers: {
    rateLimitTitle: "Richieste Troppo Rapide",
    rateLimitBody: "Hai eseguito troppi aggiornamenti della pagina in un breve intervallo di tempo. Per garantire la stabilità del servizio, le richieste frequenti sono momentaneamente limitate.",
    rateLimitHint: "Ti consigliamo di navigare all'interno dell'applicazione usando i menu e i link interni senza ricaricare l'intera pagina.",
    waitPrefix: "Attendi",
    waitSuffix: "secondi per riprovare",
    readyToRetry: "Pronto per il ripristino!",
    retrying: "Ripristino...",
    retryNow: "Riprova Ora",
    goBack: "Torna Indietro",
    authFailed: "Autenticazione Fallita",
    cleanAndRetry: "Pulisci Sessione e Riprova",
    csrfBlocked: "Errore di convalida della sessione (CSRF Blocked).",
    ssoExchangeFailed: "Impossibile completare lo scambio del codice SSO.",
    ssoNetworkError: "Errore di rete durante lo scambio del codice SSO.",
    firebaseInitError: "Errore di inizializzazione Firebase Auth: {error}. Verifica che il dominio '{domain}' sia inserito tra i referrer consentiti per la chiave API di Firebase.",
    firebaseClientAuthError: "Impossibile autenticare la sessione Firebase client: {error}. Verifica che il dominio '{domain}' sia inserito tra i referrer consentiti per la chiave API di Firebase Auth nella console Google Cloud.",
  },
  modules: {
    product: {
      title: "Prodotti e Hardware {brand}",
      description: "Gestisci e acquista sensori IoT, gateway ed estensioni hardware ufficiali {brand} per la tua infrastruttura.",
      searchPlaceholder: "Cerca prodotti per nome, SKU o tipo...",
      tableAria: "Tabella Prodotti",
      colProduct: "Prodotto",
      colSku: "SKU / Codice",
      colCategory: "Categoria",
      colPrice: "Prezzo",
      colAction: "Azione",
      notAvailable: "N/D",
      buyButton: "Acquista",
      processing: "Elaborazione...",
      emptyState: "Nessun prodotto corrisponde ai criteri di ricerca.",
      onlyAdminsBuy: "Solo l'Owner o gli Admin possono acquistare prodotti.",
      purchaseInit: "Inizializzazione acquisto per il prodotto...",
      errLoad: "Impossibile caricare i prodotti.",
      errConnection: "Errore di connessione durante il recupero dei prodotti.",
      errCheckout: "Impossibile avviare il checkout del prodotto.",
      errPurchaseStart: "Errore durante l'avvio dell'acquisto: {message}",
    },
    application: {
      title: "Applicazioni Cloud {brand}",
      description: "Gestisci gli abbonamenti SaaS ed avvia l'onboarding per le piattaforme verticali della tua organizzazione.",
      emptyState: "Nessuna applicazione disponibile nel catalogo di sistema.",
      statusSubscribed: "Abbonato",
      statusInactive: "Non Attivo",
      noDescription: "Applicazione verticale integrata per la gestione cloud enterprise.",
      expiryLabel: "Scadenza:",
      modeLabel: "Modalità:",
      priceMonthly: "{amount} € / mese",
      standardPrice: "Prezzo standard",
      autoRenewMonthly: "Rinnovo automatico mensile",
      onboardingLabel: "Onboarding Utente:",
      onboardingDone: "Completato",
      onboardingTodo: "Da completare",
      completeOnboarding: "Completa Onboarding",
      manageSubscription: "Gestisci Abbonamento",
      subscribeNow: "Abbonati Ora",
      onlyAdminsSubscribe: "Solo l'Owner o gli Admin possono abbonare l'organizzazione ai servizi.",
      onlyAdminsBilling: "Solo l'Owner o gli Admin possono gestire la fatturazione.",
      checkoutStarting: "Avvio del checkout...",
      redirectPortal: "Reindirizzamento al portale Stripe...",
      onboardingSaving: "Registrazione dell'onboarding in corso...",
      onboardingSuccess: "Onboarding completato con successo!",
      errSchema: "Risposta del server non conforme allo schema atteso.",
      errCheckoutSession: "Impossibile avviare la sessione di checkout Stripe.",
      errPaymentSession: "Errore durante la creazione della sessione di pagamento.",
      errBillingPortal: "Impossibile avviare il portale di fatturazione.",
      errStripeConnection: "Errore di connessione con Stripe.",
      errOnboardingSave: "Errore nel salvataggio dell'onboarding.",
      errOnboardingRegister: "Impossibile registrare l'onboarding.",
      errLoad: "Impossibile caricare i servizi.",
      errConnection: "Errore di connessione durante il recupero delle applicazioni.",
    },
    invoice: {
      title: "Registro Fatture e Ricevute",
      description: "Consulta lo storico cronologico di tutte le fatture ricevute per acquisti SaaS e delle fatture emesse verso clienti partner.",
      searchPlaceholder: "Cerca fattura per ID o controparte...",
      tableAria: "Tabella Fatture",
      colInvoiceId: "Fattura ID / Riferimento",
      colFlow: "Flusso",
      colCounterparty: "Controparte",
      colDate: "Data",
      colGrossAmount: "Importo Lordo",
      colStatus: "Stato",
      colActions: "Azioni",
      flowReceived: "Ricevuta",
      flowIssued: "Emessa",
      fromPrefix: "Da:",
      toPrefix: "A:",
      partnerCustomer: "Cliente Partner",
      vatDetail: "(IVA {percent}%: {amount})",
      noPdf: "Nessun PDF",
      download: "Scarica",
      filterTypeLabel: "Tipo",
      filterReceived: "Ricevute",
      filterIssued: "Emesse",
      filterAria: "Filtro flusso fatture",
      filterAllFlows: "Tutti i flussi",
      filterReceivedInvoices: "Fatture Ricevute",
      filterIssuedInvoices: "Fatture Emesse",
      emptyState: "Nessuna fattura corrisponde ai criteri impostati.",
      errLoad: "Impossibile recuperare lo storico fatture.",
      errConnection: "Errore di connessione durante il caricamento delle fatture.",
    },
    subscription: {
      title: "Piani ed Abbonamenti",
      description: "Gestisci l'abbonamento mensile, i posti dei membri (seats) ed accedi alle impostazioni di fatturazione Stripe.",
      manageOnStripe: "Gestisci su Stripe",
      pastDueTitle: "Abbonamento Insoluto!",
      pastDueBodyPrefix: "Uno o più servizi dell'organizzazione",
      pastDueBodySuffix: "risultano insoluti. Alcune funzionalità potrebbero essere sospese. Effettua il pagamento per sbloccare l'accesso.",
      payNow: "Paga Ora",
      emptyTitle: "Nessun abbonamento attivo",
      emptyBody: "Abilita una delle applicazioni verticali o API di {brand} nel catalogo servizi per iniziare.",
      seatsLabel: "Postazioni:",
      seatAssignmentTitle: "Assegnazione Licenze (Seats)",
      updating: "Aggiornamento...",
      assigned: "Assegnato",
      assign: "Assegna",
      noAdminPrivileges: "Non disponi dei privilegi di amministratore per assegnare licenze.",
      seatLimitReached: "Limite di postazioni raggiunto per questo abbonamento ({max}). Rimuovi un utente o acquistane di nuovi.",
      emailNotFound: "Email utente non trovata.",
      seatRevoked: "Licenza revocata con successo.",
      seatAssigned: "Licenza assegnata con successo.",
      errSeatUpdate: "Impossibile aggiornare la licenza.",
      errSeatUpdateDetail: "Errore durante l'aggiornamento della licenza: {message}",
      portalRedirect: "Reindirizzamento a Stripe Customer Portal in corso...",
      errPortalOpen: "Impossibile aprire il portale Stripe.",
      errStripeServer: "Errore di connessione con il server Stripe.",
      errLoadSubs: "Impossibile recuperare lo storico abbonamenti.",
      errLoadData: "Errore durante il caricamento dei dati di abbonamento.",
    },
  },
  settings: {
    totpAccountFallback: "account {issuer}",
    deviceFallback: "Dispositivo",
    browserFallback: "Browser",
    avatarAlt: "Avatar",
    subdomainPlaceholder: "la-tua-org",
    customDomainPlaceholder: "app.tuazienda.com",
    trustedTitle: "Dispositivi fidati (MFA)",
    trustedDesc: "Su questi dispositivi le operazioni sensibili non richiedono di nuovo la conferma di password/codice per 30 giorni. La fiducia si concede al login, dopo il codice di verifica.",
    trustedEmpty: "Nessun dispositivo fidato.",
    trustedLoading: "Caricamento…",
    trustedRevoke: "Revoca",
    trustedRevoked: "Fiducia del dispositivo revocata.",
    trustedRevokeFail: "Impossibile revocare il dispositivo.",
    trustedThisDevice: "Questo dispositivo",
    trustedExpires: "Scade il {date}",
  },
  dialogs: {
    support: {
      title: "Supporto Virtuale {brand}",
      subtitle: "AI Agent attivo",
      greeting: "Ciao! Sono l'assistente virtuale di {brand} Cloud. Come posso aiutarti oggi con i nostri prodotti o servizi?",
      promptApiKey: "Come genero una chiave API?",
      promptStripe: "Come funziona l'onboarding Stripe?",
      promptFls: "Cos'è la protezione FLS?",
      promptTheme: "Come cambio lingua o tema?",
      answerFallback: "Mi dispiace, non ho capito la richiesta. Puoi riformulare la domanda sui servizi {brand}?",
      answerApiKey: "Per generare una chiave API su {brand}:\n1. Accedi alla sezione **API Key** dal menu laterale.\n2. Clicca su **Crea Chiave**.\n3. Specifica i permessi per ciascun modulo e clicca su Genera.\n\n*Nota: Ricorda di salvare la chiave subito, non verrà mostrata una seconda volta per ragioni di sicurezza.*",
      answerStripe: "L'onboarding di Stripe ti consente di attivare i pagamenti. Puoi completarlo accedendo alla sezione **Payment** o dalla pagina del profilo dell'organizzazione, dove verrai reindirizzato su Stripe Connect per inserire i dati fiscali della tua azienda.",
      answerFls: "{brand} adotta una sicurezza a livello di singolo campo (Field-Level Security - FLS) e RBAC. Le politiche sono definite staticamente in `resources.config.ts`. Solo gli utenti con ruolo `owner` scavalcano questi controlli, mentre per gli altri ruoli le proprietà in ingresso e in uscita vengono filtrate automaticamente.",
      answerTheme: "Puoi cambiare il tema (chiaro/scuro) cliccando sull'icona del sole/luna in basso a sinistra della sidebar. La lingua viene gestita in base al locale impostato nell'URL (it/en/es) ed è modificabile dal pannello impostazioni utente.",
      answerGreeting: "Ciao! Come posso esserti utile oggi? Posso spiegarti come funzionano le API Key, l'onboarding Stripe, o le nostre politiche di sicurezza.",
      suggestionsLabel: "Suggerimenti rapidi:",
      inputPlaceholder: "Fai una domanda sul supporto {brand}...",
    },
    ai: {
      title: "Analizzatore Dati AI {brand}",
      subtitle: "Gemini Agent integrato",
      greeting: "Ciao! Sono l'agente di Analisi AI di {brand}. Sono connesso in tempo reale ai tuoi dati di sessione e dell'organizzazione. Chiedimi pure un'analisi strutturata o informazioni sulle risorse attive.",
      promptOrg: "Analizza la mia organizzazione",
      promptSubs: "Mostra lo stato delle mie subscription",
      promptRole: "Quali permessi ha il mio ruolo?",
      answerFallback: "Non ho elementi sufficienti per analizzare questa specifica richiesta. Prova a chiedermi un report dell'organizzazione o lo stato dei servizi.",
      orgNone: "Nessuna Organizzazione Associata",
      orgReport: "Ecco l'analisi dei dati per l'organizzazione **{org}**:\n- **Stato Onboarding**: {onboarding}\n- **Tipo Organizzazione**: {type}\n- **Paese di Registrazione**: {country}\n- **Modalità Ambiente**: {env}\n- **Verifica P.IVA (VIES)**: {vies}\n\n*Il tuo ruolo all'interno di questa organizzazione è **{role}**, che ti garantisce la visibilità delle risorse.*",
      orgConfirmed: "🟢 Confermato ed Attivo",
      orgPending: "🟡 In attesa / Da confermare",
      orgTypeStandard: "Standard",
      orgCountryUnknown: "Non Specificato",
      envTest: "🧪 Test Environment",
      envProd: "⚡ Production Live",
      viesOk: "✅ Validata con successo",
      viesKo: "❌ Non validata o non presente",
      subsEmpty: "Per l'organizzazione **{org}** non risultano licenze o abbonamenti attivi al momento. Puoi attivarne uno dalla sezione **Product** del nostro portale.",
      subsFound: "Ho trovato **{count}** abbonamenti attivi per **{org}**:",
      subItem: "{index}. **Servizio**: {service}\n   - **Stato**: {status}\n   - **Rinnovo Automatico**: {renewal}\n   - **Scadenza Periodo**: {expiry}",
      subStatusActive: "🟢 Attivo",
      subStatusOther: "🟡 {status}",
      renewalOff: "❌ Disattivato",
      renewalOn: "✅ Attivo",
      notAvailable: "N/D",
      roleReport: "Analisi dei privilegi per l'utente loggato:\n- **Ruolo Assegnato**: `{role}`\n- **Bypass RBAC/FLS**: {bypass}\n\nI tuoi permessi operativi ti consentono di visualizzare e gestire le risorse in conformità con il registro statico di sicurezza di {brand} per l'applicazione corrente.",
      bypassOn: "✅ Abilitato (Bypass completo)",
      bypassOff: "❌ Disabilitato (Soggetto a policy)",
      answerGreeting: "Ciao! Posso eseguire un'analisi dei tuoi dati in tempo reale. Chiedimi pure un riassunto dell'organizzazione o lo stato degli abbonamenti attivi.",
      suggestionsLabel: "Suggerimenti rapidi:",
      inputPlaceholder: "Chiedi un'analisi all'AI di {brand}...",
    },
    stripeConnect: {
      errStatusFetch: "Errore durante il recupero dello stato dell'account.",
      errStatusNetwork: "Errore di rete durante la verifica dello stato.",
      errOnboardLink: "Impossibile generare il link di onboarding.",
      errStripeConnection: "Errore di connessione a Stripe.",
      errDashboardLink: "Impossibile generare il link per la dashboard.",
      errLinkGeneration: "Errore durante la generazione del link.",
      accessDeniedTitle: "Accesso Limitato",
      accessDeniedBody: "Solo il proprietario dell'organizzazione (**owner**) possiede le autorizzazioni necessarie per configurare i conti bancari, attivare Stripe Connect o gestire le impostazioni di incasso e payout per i partner.",
      currentRoleLabel: "Il tuo ruolo attuale:",
      roleFallback: "Membro",
      pageTitle: "Configurazione Stripe Connect",
      pageDesc: "Abilita la ricezione dei pagamenti e gestisci il split-billing per i progetti in cui collabori come organizzazione partner.",
      activeTitle: "Stripe Connect Attivo",
      activeBadge: "Attivo",
      accountIdLabel: "ID Account:",
      expressConsole: "Console Express Stripe",
      chargesLabel: "Ricezione Pagamenti",
      chargesEnabled: "Abilitata - Puoi incassare split-billing",
      chargesDisabled: "Sospesa o limitata",
      payoutsLabel: "Invio Bonifici (Payout)",
      payoutsEnabled: "Abilitato - Bonifici automatici attivi",
      payoutsDisabled: "Sospeso o in verifica",
      futureChecksTitle: "Verifiche future previste:",
      futureChecksBody: "Stripe potrebbe richiedere ulteriori informazioni in futuro qualora superassi determinate soglie di incasso (es. {list}).",
      incompleteTitle: "Configurazione Incompleta",
      kycBadge: "KYC Richiesto",
      completeSetup: "Completa Configurazione",
      kycNotice: "Stripe richiede ulteriori informazioni di identificazione (KYC) per attivare i payout:",
      kycFallback: "Completa i passaggi richiesti sul portale di Stripe Connect per poter abilitare i pagamenti.",
      enableTitle: "Abilita Stripe Connect per la tua Organizzazione",
      enableBody: "Connetti in sicurezza un conto corrente o carta di debito bancaria tramite Stripe Connect Express. Abilitando Connect, la tua organizzazione potrà vendere beni hardware, offrire licenze o configurare flussi di fatturazione ricorrente split-billing con altre organizzazioni partner all'interno del network {brand}.",
      safeOnboardingTitle: "Onboarding Semplice & Sicuro:",
      safeOnboardingBody: "Stripe Express gestisce direttamente i requisiti antiriciclaggio e fiscali (KYC). {brand} non memorizza in alcun modo i tuoi estremi bancari. La commissione sulla piattaforma per le transazioni split Connect è fissata all'1%.",
      enableCta: "Attiva Stripe Connect",
    },
  },
} as const;

/** Mappa ricorsivamente ogni foglia del dizionario su `string` (preserva i namespace annidati). */
type DeepStrings<T> = {
  readonly [K in keyof T]: T[K] extends string ? string : DeepStrings<T[K]>;
};

/** Forma canonica del dizionario UI (derivata dall'italiano). */
export type UIStrings = DeepStrings<typeof it>;

const en: UIStrings = {
  common: {
    save: "Save",
    close: "Close",
    cancel: "Cancel",
    search: "Search...",
    copyToClipboard: "Copy to clipboard",
    closeNotification: "Close notification",
    closeDetails: "Close details",
    user: "User",
    userMenu: "User menu",
    loading: "Loading…",
    sessionSync: "Synchronizing session…",
    showPassword: "Show password",
    hidePassword: "Hide password",
    capsLockOn: "Caps Lock is on",
  },
  validation: {
    number: "Must be a number",
    email: "Invalid email address",
    vat: "Invalid VAT number",
    personalId: "Invalid tax code (16 characters)",
    sdi: "Invalid SDI code (7 characters)",
    required: "Required field",
    min: "Minimum {n} characters",
    max: "Maximum {n} characters",
  },
  auth: {
    emailLabel: "Email Address",
    emailPlaceholder: "name@example.com",
    passwordLabel: "Password",
    passwordPlaceholder: "••••••••",
    rememberMe: "Remember me",
    forgotPassword: "Forgot your password?",
    signIn: "Sign in",
    signingIn: "Signing in…",
    noAccount: "Don't have an account yet?",
    registerNow: "Register now",
    backToLogin: "Back to login / Sign out",
    hasAccount: "Already have an account?",
    loginHere: "Login here",
    register: {
      typePersonal: "Personal",
      typeBusiness: "Business",
      typeGovernment: "Public Admin",
      typeEducation: "Edu",
      name: "Full Name",
      fiscalCountry: "Tax Country (Residence)",
      country: "Country",
      passwordStrength: "Password strength:",
      passwordTooShort: "Too short",
      passwordWeak: "Weak",
      passwordMedium: "Medium",
      passwordStrong: "Strong ✨",
      vatNumberPersonalIT: "Tax Code (Optional)",
      vatNumberPersonalES: "DNI / NIE / NIF (Optional)",
      vatNumberPersonalGeneric: "Tax ID / NIF (Optional)",
      vatNumberPersonalPlaceholderIT: "e.g. RSSMRA80A01H501U",
      vatNumberPersonalPlaceholderES: "e.g. 12345678A or Y1234567Z",
      vatNumberPersonalPlaceholderGeneric: "e.g. Local Tax ID",
      residenceAddress: "Residence Address",
      addressPlaceholder: "Start typing the address...",
      orgDetails: "Organization Details",
      vatNumberIT: "VAT Number",
      vatNumberES: "NIF / CIF (Spain)",
      vatNumberGeneric: "VAT Number / Tax ID",
      viesValidated: "Validated via European Commission VIES ✨",
      vatWarningInfo: "Tax Information (Directive 2006/112/EC): The VAT number entered is not registered or enabled in the VIES system for intra-Community transactions. Registration is permitted; however, invoices will be subject to the standard VAT rate of the member State of establishment (VAT inclusive), excluding the reverse charge mechanism.",
      viesOfflineWarning: "The VIES validation service is temporarily offline. Registration is permitted, but the eligibility for the intra-Community VAT exemption will be verified later.",
      companyNameBusiness: "Company Legal Name",
      companyNameGovernment: "Public Entity Name",
      companyNameEducation: "Institution / University Name",
      companyNamePlaceholderBusiness: "ACME S.r.l.",
      companyNamePlaceholderGovernment: "Ministry of Interior",
      companyNamePlaceholderEducation: "University / High School Name",
      legalAddress: "Official Registered Office Address",
      sdiCode: "SDI Recipient Code (Optional)",
      sdiPlaceholder: "7 characters",
      officeCode: "PA Office Code (IPA) - Required",
      officePlaceholder: "6 characters",
      cigCode: "CIG Code (Optional)",
      cupCode: "CUP Code (Optional)",
      acceptTerms: "I accept the privacy policy and terms of service.",
      acceptTermsPrefix: "I accept the",
      privacyPolicy: "privacy policy",
      acceptTermsConj: "and",
      termsOfService: "terms of service",
      acceptTermsSuffix: ".",
      register: "Sign Up",
    },
    mfa: {
      title: "Two-Factor Authentication",
      totpPrompt: "Enter the 6-digit code generated by {factor}.",
      code: "Verification code",
      submit: "Verify code",
      backupCta: "Lost your device? Use a backup code",
      backupPrompt: "Enter one of the backup codes you saved when setting up 2FA. We'll reset the second factor; then sign in with your password.",
      backupSubmit: "Reset",
      backupCancel: "Cancel",
      trustDevice: "Trust this device for 30 days",
    },
    reauth: {
      title: "Confirm your identity",
      passwordPrompt: "To continue with this sensitive operation, confirm your password.",
      mfaPrompt: "Enter the 6-digit code generated by {factor} to continue.",
      confirm: "Confirm",
      verifying: "Verifying…",
    },
    mfaEnroll: {
      title: "Set up your authenticator app",
      instructions: "Scan the QR code with your authenticator app (Google Authenticator, 1Password…) or enter the key manually, then confirm the first generated code.",
      scanHint: "Scan with the app",
      manualKeyLabel: "Manual key",
      openInApp: "Open in authenticator app",
      copyKey: "Copy the key",
      confirm: "Confirm",
    },
    mfaBackup: {
      warning: "Store these codes somewhere safe: they will not be shown again. Each code works only once.",
      copy: "Copy",
      download: "Download .txt",
      done: "Done, I saved them",
    },
    reset: {
      title: "Reset Password",
      sendLink: "Send reset link",
      newPassword: "New Password",
      confirmPassword: "Confirm Password",
      forLabel: "For:",
    },
    verify: {
      title: "Verify your Email",
      desc: "We sent a verification link to {email}. Check your inbox and click the link to activate your account.",
      button: "I verified my email (Refresh)",
      resendEmailButton: "Resend Verification Email",
      resendCooldown: "Resend in {n}s",
    },
  },
  layout: {
    errorTitle: "An error occurred",
    authCheck: "Verifying authentication...",
    secureRedirect: "Secure redirect to the authentication portal...",
    orgSetupTitle: "Organization Setup",
    onboardingInProgress: "Organization onboarding in progress...",
    invalidServerData: "The data received from the server is invalid. Reload the page or contact support.",
    claimsAlignError: "Unable to align the profile organization. Contact support.",
    skipToContent: "Skip to main content",
    mainNavAria: "Main navigation",
    footerNavAria: "Footer links",
    rightsReserved: "All rights reserved.",
    openMenu: "Open the navigation menu",
    contentErrorTitle: "Something went wrong",
    contentErrorBody: "The content cannot be displayed. Retry or reload the page.",
    retry: "Retry",
    palette: {
      title: "Command palette",
      placeholder: "Go to module…",
      noResults: "No module found",
      hint: "navigate",
    },
    views: {
      empty: {
        title: "Nothing to show",
        description: "There are no items to display here.",
      },
      switcher: {
        list: "List view",
        kanban: "Kanban view",
        gantt: "Gantt view",
      },
      kanban: {
        itemCount: "{n} items",
        columnEmpty: "No items",
      },
      gantt: {
        week: "Week",
        month: "Month",
        today: "Today",
        withoutDates: "{n} items without dates not shown",
      },
    },
  },
  sidebar: {
    collapse: "Collapse Sidebar",
    expand: "Expand Sidebar",
    notifications: "Notifications",
    messages: "Messages",
    serviceStatus: "Service Status",
    serviceStatusOk: "Service Status: OK",
    changeTheme: "Toggle Theme",
    themeLabel: "Theme: {mode}",
    settings: "Settings",
    support: "Support",
    openSupport: "Open Support",
    aiAgent: "AI Agent",
    logout: "Log out",
    disconnect: "Sign out",
  },
  form: {
    noPermission: "You do not have the required permissions to fill in this form.",
    submitError: "An error occurred while submitting.",
  },
  filter: {
    activeFilters: "Active filters:",
    removeAll: "Remove all",
    removeFilter: "Remove filter {label}",
  },
  providers: {
    rateLimitTitle: "Too Many Requests",
    rateLimitBody: "You have refreshed the page too many times in a short time span. To keep the service stable, frequent requests are temporarily limited.",
    rateLimitHint: "We recommend navigating within the application using menus and internal links without reloading the whole page.",
    waitPrefix: "Wait",
    waitSuffix: "seconds before retrying",
    readyToRetry: "Ready to retry!",
    retrying: "Retrying...",
    retryNow: "Retry Now",
    goBack: "Go Back",
    authFailed: "Authentication Failed",
    cleanAndRetry: "Clean Session and Retry",
    csrfBlocked: "Session validation error (CSRF Blocked).",
    ssoExchangeFailed: "Unable to complete the SSO code exchange.",
    ssoNetworkError: "Network error during the SSO code exchange.",
    firebaseInitError: "Firebase Auth initialization error: {error}. Make sure the domain '{domain}' is listed among the allowed referrers for the Firebase API key.",
    firebaseClientAuthError: "Unable to authenticate the Firebase client session: {error}. Make sure the domain '{domain}' is listed among the allowed referrers for the Firebase Auth API key in the Google Cloud console.",
  },
  modules: {
    product: {
      title: "{brand} Products and Hardware",
      description: "Manage and purchase official {brand} IoT sensors, gateways and hardware extensions for your infrastructure.",
      searchPlaceholder: "Search products by name, SKU or type...",
      tableAria: "Products Table",
      colProduct: "Product",
      colSku: "SKU / Code",
      colCategory: "Category",
      colPrice: "Price",
      colAction: "Action",
      notAvailable: "N/A",
      buyButton: "Buy",
      processing: "Processing...",
      emptyState: "No product matches the search criteria.",
      onlyAdminsBuy: "Only the Owner or Admins can purchase products.",
      purchaseInit: "Initializing product purchase...",
      errLoad: "Unable to load products.",
      errConnection: "Connection error while retrieving products.",
      errCheckout: "Unable to start the product checkout.",
      errPurchaseStart: "Error while starting the purchase: {message}",
    },
    application: {
      title: "{brand} Cloud Applications",
      description: "Manage SaaS subscriptions and start the onboarding for your organization's vertical platforms.",
      emptyState: "No application available in the system catalog.",
      statusSubscribed: "Subscribed",
      statusInactive: "Not Active",
      noDescription: "Integrated vertical application for enterprise cloud management.",
      expiryLabel: "Expires:",
      modeLabel: "Mode:",
      priceMonthly: "{amount} € / month",
      standardPrice: "Standard price",
      autoRenewMonthly: "Automatic monthly renewal",
      onboardingLabel: "User Onboarding:",
      onboardingDone: "Completed",
      onboardingTodo: "To complete",
      completeOnboarding: "Complete Onboarding",
      manageSubscription: "Manage Subscription",
      subscribeNow: "Subscribe Now",
      onlyAdminsSubscribe: "Only the Owner or Admins can subscribe the organization to services.",
      onlyAdminsBilling: "Only the Owner or Admins can manage billing.",
      checkoutStarting: "Starting checkout...",
      redirectPortal: "Redirecting to the Stripe portal...",
      onboardingSaving: "Recording the onboarding...",
      onboardingSuccess: "Onboarding completed successfully!",
      errSchema: "Server response does not match the expected schema.",
      errCheckoutSession: "Unable to start the Stripe checkout session.",
      errPaymentSession: "Error while creating the payment session.",
      errBillingPortal: "Unable to open the billing portal.",
      errStripeConnection: "Connection error with Stripe.",
      errOnboardingSave: "Error while saving the onboarding.",
      errOnboardingRegister: "Unable to record the onboarding.",
      errLoad: "Unable to load services.",
      errConnection: "Connection error while retrieving applications.",
    },
    invoice: {
      title: "Invoices and Receipts Register",
      description: "Browse the chronological history of all invoices received for SaaS purchases and invoices issued to partner customers.",
      searchPlaceholder: "Search invoice by ID or counterparty...",
      tableAria: "Invoices Table",
      colInvoiceId: "Invoice ID / Reference",
      colFlow: "Flow",
      colCounterparty: "Counterparty",
      colDate: "Date",
      colGrossAmount: "Gross Amount",
      colStatus: "Status",
      colActions: "Actions",
      flowReceived: "Received",
      flowIssued: "Issued",
      fromPrefix: "From:",
      toPrefix: "To:",
      partnerCustomer: "Partner Customer",
      vatDetail: "(VAT {percent}%: {amount})",
      noPdf: "No PDF",
      download: "Download",
      filterTypeLabel: "Type",
      filterReceived: "Received",
      filterIssued: "Issued",
      filterAria: "Invoice flow filter",
      filterAllFlows: "All flows",
      filterReceivedInvoices: "Received Invoices",
      filterIssuedInvoices: "Issued Invoices",
      emptyState: "No invoice matches the selected criteria.",
      errLoad: "Unable to retrieve the invoice history.",
      errConnection: "Connection error while loading invoices.",
    },
    subscription: {
      title: "Plans and Subscriptions",
      description: "Manage the monthly subscription, member seats and access the Stripe billing settings.",
      manageOnStripe: "Manage on Stripe",
      pastDueTitle: "Subscription Past Due!",
      pastDueBodyPrefix: "One or more services of the organization",
      pastDueBodySuffix: "are past due. Some features may be suspended. Complete the payment to restore access.",
      payNow: "Pay Now",
      emptyTitle: "No active subscription",
      emptyBody: "Enable one of the {brand} vertical applications or APIs in the service catalog to get started.",
      seatsLabel: "Seats:",
      seatAssignmentTitle: "License Assignment (Seats)",
      updating: "Updating...",
      assigned: "Assigned",
      assign: "Assign",
      noAdminPrivileges: "You do not have administrator privileges to assign licenses.",
      seatLimitReached: "Seat limit reached for this subscription ({max}). Remove a user or purchase new seats.",
      emailNotFound: "User email not found.",
      seatRevoked: "License revoked successfully.",
      seatAssigned: "License assigned successfully.",
      errSeatUpdate: "Unable to update the license.",
      errSeatUpdateDetail: "Error while updating the license: {message}",
      portalRedirect: "Redirecting to the Stripe Customer Portal...",
      errPortalOpen: "Unable to open the Stripe portal.",
      errStripeServer: "Connection error with the Stripe server.",
      errLoadSubs: "Unable to retrieve the subscription history.",
      errLoadData: "Error while loading subscription data.",
    },
  },
  settings: {
    totpAccountFallback: "account {issuer}",
    deviceFallback: "Device",
    browserFallback: "Browser",
    avatarAlt: "Avatar",
    subdomainPlaceholder: "your-org",
    customDomainPlaceholder: "app.yourcompany.com",
    trustedTitle: "Trusted devices (MFA)",
    trustedDesc: "On these devices, sensitive operations will not ask for your password/code again for 30 days. Trust is granted at login, after the verification code.",
    trustedEmpty: "No trusted devices.",
    trustedLoading: "Loading…",
    trustedRevoke: "Revoke",
    trustedRevoked: "Device trust revoked.",
    trustedRevokeFail: "Could not revoke the device.",
    trustedThisDevice: "This device",
    trustedExpires: "Expires on {date}",
  },
  dialogs: {
    support: {
      title: "{brand} Virtual Support",
      subtitle: "AI Agent active",
      greeting: "Hi! I'm the {brand} Cloud virtual assistant. How can I help you today with our products or services?",
      promptApiKey: "How do I generate an API key?",
      promptStripe: "How does the Stripe onboarding work?",
      promptFls: "What is FLS protection?",
      promptTheme: "How do I change language or theme?",
      answerFallback: "I'm sorry, I didn't understand your request. Could you rephrase your question about {brand} services?",
      answerApiKey: "To generate an API key on {brand}:\n1. Open the **API Key** section from the side menu.\n2. Click **Create Key**.\n3. Set the permissions for each module and click Generate.\n\n*Note: Remember to save the key right away, for security reasons it will not be shown a second time.*",
      answerStripe: "The Stripe onboarding lets you activate payments. You can complete it from the **Payment** section or from the organization profile page, where you will be redirected to Stripe Connect to enter your company's fiscal details.",
      answerFls: "{brand} adopts field-level security (Field-Level Security - FLS) and RBAC. Policies are statically defined in `resources.config.ts`. Only users with the `owner` role bypass these controls, while for all other roles incoming and outgoing properties are filtered automatically.",
      answerTheme: "You can switch the theme (light/dark) by clicking the sun/moon icon at the bottom left of the sidebar. The language is driven by the locale set in the URL (it/en/es) and can be changed from the user settings panel.",
      answerGreeting: "Hi! How can I help you today? I can explain how API Keys work, the Stripe onboarding, or our security policies.",
      suggestionsLabel: "Quick suggestions:",
      inputPlaceholder: "Ask a question about {brand} support...",
    },
    ai: {
      title: "{brand} AI Data Analyzer",
      subtitle: "Integrated Gemini Agent",
      greeting: "Hi! I'm the {brand} AI Analysis agent. I'm connected in real time to your session and organization data. Feel free to ask me for a structured analysis or information about active resources.",
      promptOrg: "Analyze my organization",
      promptSubs: "Show the status of my subscriptions",
      promptRole: "Which permissions does my role have?",
      answerFallback: "I don't have enough elements to analyze this specific request. Try asking me for an organization report or the status of your services.",
      orgNone: "No Associated Organization",
      orgReport: "Here is the data analysis for the organization **{org}**:\n- **Onboarding Status**: {onboarding}\n- **Organization Type**: {type}\n- **Country of Registration**: {country}\n- **Environment Mode**: {env}\n- **VAT Check (VIES)**: {vies}\n\n*Your role within this organization is **{role}**, which grants you visibility over its resources.*",
      orgConfirmed: "🟢 Confirmed and Active",
      orgPending: "🟡 Pending / To be confirmed",
      orgTypeStandard: "Standard",
      orgCountryUnknown: "Not Specified",
      envTest: "🧪 Test Environment",
      envProd: "⚡ Production Live",
      viesOk: "✅ Successfully validated",
      viesKo: "❌ Not validated or missing",
      subsEmpty: "No active licenses or subscriptions found for the organization **{org}** at the moment. You can activate one from the **Product** section of our portal.",
      subsFound: "I found **{count}** active subscriptions for **{org}**:",
      subItem: "{index}. **Service**: {service}\n   - **Status**: {status}\n   - **Auto Renewal**: {renewal}\n   - **Period End**: {expiry}",
      subStatusActive: "🟢 Active",
      subStatusOther: "🟡 {status}",
      renewalOff: "❌ Disabled",
      renewalOn: "✅ Active",
      notAvailable: "N/A",
      roleReport: "Privilege analysis for the logged-in user:\n- **Assigned Role**: `{role}`\n- **RBAC/FLS Bypass**: {bypass}\n\nYour operational permissions allow you to view and manage resources in compliance with the static {brand} security registry for the current application.",
      bypassOn: "✅ Enabled (Full bypass)",
      bypassOff: "❌ Disabled (Subject to policies)",
      answerGreeting: "Hi! I can run an analysis of your data in real time. Feel free to ask me for an organization summary or the status of your active subscriptions.",
      suggestionsLabel: "Quick suggestions:",
      inputPlaceholder: "Ask the {brand} AI for an analysis...",
    },
    stripeConnect: {
      errStatusFetch: "Error while retrieving the account status.",
      errStatusNetwork: "Network error while checking the status.",
      errOnboardLink: "Unable to generate the onboarding link.",
      errStripeConnection: "Connection error with Stripe.",
      errDashboardLink: "Unable to generate the dashboard link.",
      errLinkGeneration: "Error while generating the link.",
      accessDeniedTitle: "Restricted Access",
      accessDeniedBody: "Only the organization owner (**owner**) has the permissions required to configure bank accounts, activate Stripe Connect or manage collection and payout settings for partners.",
      currentRoleLabel: "Your current role:",
      roleFallback: "Member",
      pageTitle: "Stripe Connect Configuration",
      pageDesc: "Enable payment collection and manage split-billing for the projects where you collaborate as a partner organization.",
      activeTitle: "Stripe Connect Active",
      activeBadge: "Active",
      accountIdLabel: "Account ID:",
      expressConsole: "Stripe Express Console",
      chargesLabel: "Payment Collection",
      chargesEnabled: "Enabled - You can collect split-billing",
      chargesDisabled: "Suspended or limited",
      payoutsLabel: "Bank Transfers (Payout)",
      payoutsEnabled: "Enabled - Automatic payouts active",
      payoutsDisabled: "Suspended or under review",
      futureChecksTitle: "Expected future checks:",
      futureChecksBody: "Stripe may request additional information in the future should you exceed certain collection thresholds (e.g. {list}).",
      incompleteTitle: "Incomplete Configuration",
      kycBadge: "KYC Required",
      completeSetup: "Complete Configuration",
      kycNotice: "Stripe requires additional identification information (KYC) to enable payouts:",
      kycFallback: "Complete the required steps on the Stripe Connect portal to enable payments.",
      enableTitle: "Enable Stripe Connect for your Organization",
      enableBody: "Securely connect a bank account or bank debit card through Stripe Connect Express. By enabling Connect, your organization will be able to sell hardware goods, offer licenses or set up recurring split-billing flows with other partner organizations within the {brand} network.",
      safeOnboardingTitle: "Simple & Secure Onboarding:",
      safeOnboardingBody: "Stripe Express directly handles anti-money-laundering and fiscal requirements (KYC). {brand} never stores your bank details in any way. The platform fee for split Connect transactions is set at 1%.",
      enableCta: "Activate Stripe Connect",
    },
  },
};

const es: UIStrings = {
  common: {
    save: "Guardar",
    close: "Cerrar",
    cancel: "Cancelar",
    search: "Buscar...",
    copyToClipboard: "Copiar al portapapeles",
    closeNotification: "Cerrar notificación",
    closeDetails: "Cerrar detalles",
    user: "Usuario",
    userMenu: "Menú de usuario",
    loading: "Cargando…",
    sessionSync: "Sincronizando sesión…",
    showPassword: "Mostrar contraseña",
    hidePassword: "Ocultar contraseña",
    capsLockOn: "Bloq Mayús activado",
  },
  validation: {
    number: "Debe ser un número",
    email: "Correo electrónico no válido",
    vat: "Número de IVA no válido",
    personalId: "Código fiscal no válido (16 caracteres)",
    sdi: "Código SDI no válido (7 caracteres)",
    required: "Campo obligatorio",
    min: "Mínimo {n} caracteres",
    max: "Máximo {n} caracteres",
  },
  auth: {
    emailLabel: "Dirección de correo",
    emailPlaceholder: "name@example.com",
    passwordLabel: "Contraseña",
    passwordPlaceholder: "••••••••",
    rememberMe: "Recuérdame",
    forgotPassword: "¿Olvidaste la contraseña?",
    signIn: "Iniciar sesión",
    signingIn: "Iniciando sesión…",
    noAccount: "¿Aún no tienes una cuenta?",
    registerNow: "Regístrate ahora",
    backToLogin: "Volver al inicio de sesión / Salir",
    hasAccount: "¿Ya tienes una cuenta?",
    loginHere: "Inicia sesión aquí",
    register: {
      typePersonal: "Particular",
      typeBusiness: "Empresa",
      typeGovernment: "Adm. Pública",
      typeEducation: "Edu",
      name: "Nombre Completo",
      fiscalCountry: "Nación Fiscal (Residencia)",
      country: "País",
      passwordStrength: "Fuerza de la contraseña:",
      passwordTooShort: "Demasiado corta",
      passwordWeak: "Débil",
      passwordMedium: "Media",
      passwordStrong: "Fuerte ✨",
      vatNumberPersonalIT: "Código Fiscal (Opcional)",
      vatNumberPersonalES: "DNI / NIE / NIF (Opcional)",
      vatNumberPersonalGeneric: "Identificación Fiscal / NIF (Opcional)",
      vatNumberPersonalPlaceholderIT: "ej. RSSMRA80A01H501U",
      vatNumberPersonalPlaceholderES: "ej. 12345678A o Y1234567Z",
      vatNumberPersonalPlaceholderGeneric: "ej. Identificación Fiscal local",
      residenceAddress: "Dirección de Residencia",
      addressPlaceholder: "Comienza a escribir la dirección...",
      orgDetails: "Detalles de la Organización",
      vatNumberIT: "Partida IVA",
      vatNumberES: "NIF / CIF",
      vatNumberGeneric: "Número de IVA / Tax ID",
      viesValidated: "Validado a través de VIES Comisión Europea ✨",
      vatWarningInfo: "Información Fiscal (Directiva 2006/112/CE): El número de IVA introducido no figura como registrado o habilitado en el sistema VIES para operaciones intracomunitarias. Se permite el registro; sin embargo, las facturas estarán sujetas al tipo general del IVA del Estado miembro de establecimiento (IVA incluido), excluyendo el régimen de inversión del sujeto pasivo (Reverse Charge).",
      viesOfflineWarning: "El servicio de validación VIES está temporalmente fuera de línea. Se permite el registro, pero la aplicación del régimen de exención del IVA intracomunitario se verificará posteriormente.",
      companyNameBusiness: "Razón Social de la Empresa",
      companyNameGovernment: "Nombre de la Entidad Pública",
      companyNameEducation: "Nombre del Instituto / Universidad",
      companyNamePlaceholderBusiness: "ACME S.r.l.",
      companyNamePlaceholderGovernment: "Ministerio del Interior",
      companyNamePlaceholderEducation: "Universidad / Instituto Escolar",
      legalAddress: "Dirección Oficial del Domicilio Social",
      sdiCode: "Código del Destinatario SDI (Opcional)",
      sdiPlaceholder: "7 caracteres",
      officeCode: "Código de Oficina PA (IPA) - Requerido",
      officePlaceholder: "6 caracteres",
      cigCode: "Código CIG (Opcional)",
      cupCode: "Código CUP (Opcional)",
      acceptTerms: "Acepto la política de privacidad y los términos de servicio.",
      acceptTermsPrefix: "Acepto la",
      privacyPolicy: "política de privacidad",
      acceptTermsConj: "y los",
      termsOfService: "términos de servicio",
      acceptTermsSuffix: ".",
      register: "Registrarse",
    },
    mfa: {
      title: "Autenticación de Dos Factores",
      totpPrompt: "Introduce el código de 6 dígitos generado por {factor}.",
      code: "Código de verificación",
      submit: "Verificar código",
      backupCta: "¿Perdiste tu dispositivo? Usa un código de respaldo",
      backupPrompt: "Introduce uno de los códigos de respaldo que guardaste al configurar la 2FA. Restableceremos el segundo factor; luego inicia sesión con tu contraseña.",
      backupSubmit: "Restablecer",
      backupCancel: "Cancelar",
      trustDevice: "Confiar en este dispositivo durante 30 días",
    },
    reauth: {
      title: "Confirma tu identidad",
      passwordPrompt: "Para continuar con esta operación sensible, confirma tu contraseña.",
      mfaPrompt: "Introduce el código de 6 dígitos generado por {factor} para continuar.",
      confirm: "Confirmar",
      verifying: "Verificando…",
    },
    mfaEnroll: {
      title: "Configura tu app de autenticación",
      instructions: "Escanea el código QR con tu app de autenticación (Google Authenticator, 1Password…) o introduce la clave manualmente, y confirma el primer código generado.",
      scanHint: "Escanea con la app",
      manualKeyLabel: "Clave manual",
      openInApp: "Abrir en la app de autenticación",
      copyKey: "Copiar la clave",
      confirm: "Confirmar",
    },
    mfaBackup: {
      warning: "Guarda estos códigos en un lugar seguro: no se mostrarán de nuevo. Cada código funciona una sola vez.",
      copy: "Copiar",
      download: "Descargar .txt",
      done: "Listo, los he guardado",
    },
    reset: {
      title: "Restablecer Contraseña",
      sendLink: "Enviar enlace de restablecimiento",
      newPassword: "Nueva Contraseña",
      confirmPassword: "Confirmar Contraseña",
      forLabel: "Para:",
    },
    verify: {
      title: "Verifica tu Correo",
      desc: "Hemos enviado un enlace de verificación a {email}. Revisa tu bandeja de entrada y haz clic en el enlace para activar tu cuenta.",
      button: "He verificado el correo (Actualizar)",
      resendEmailButton: "Reenviar correo de verificación",
      resendCooldown: "Reenviar en {n}s",
    },
  },
  layout: {
    errorTitle: "Se ha producido un error",
    authCheck: "Verificando autenticación...",
    secureRedirect: "Redirección segura al portal de autenticación...",
    orgSetupTitle: "Configuración de la Organización",
    onboardingInProgress: "Incorporación de la organización en curso...",
    invalidServerData: "Los datos recibidos del servidor no son válidos. Recarga la página o contacta con el soporte.",
    claimsAlignError: "No se puede alinear la organización del perfil. Contacta con el soporte.",
    skipToContent: "Saltar al contenido principal",
    mainNavAria: "Navegación principal",
    footerNavAria: "Enlaces de pie de página",
    rightsReserved: "Todos los derechos reservados.",
    openMenu: "Abrir el menú de navegación",
    contentErrorTitle: "Algo salió mal",
    contentErrorBody: "El contenido no se puede mostrar. Reintenta o recarga la página.",
    retry: "Reintentar",
    palette: {
      title: "Paleta de comandos",
      placeholder: "Ir al módulo…",
      noResults: "Ningún módulo encontrado",
      hint: "navegar",
    },
    views: {
      empty: {
        title: "Nada que mostrar",
        description: "No hay elementos para mostrar aquí.",
      },
      switcher: {
        list: "Vista de lista",
        kanban: "Vista kanban",
        gantt: "Vista Gantt",
      },
      kanban: {
        itemCount: "{n} elementos",
        columnEmpty: "Sin elementos",
      },
      gantt: {
        week: "Semana",
        month: "Mes",
        today: "Hoy",
        withoutDates: "{n} elementos sin fechas no mostrados",
      },
    },
  },
  sidebar: {
    collapse: "Contraer barra lateral",
    expand: "Expandir barra lateral",
    notifications: "Notificaciones",
    messages: "Mensajes",
    serviceStatus: "Estado del Servicio",
    serviceStatusOk: "Estado del Servicio: OK",
    changeTheme: "Cambiar Tema",
    themeLabel: "Tema: {mode}",
    settings: "Configuración",
    support: "Soporte",
    openSupport: "Abrir Soporte",
    aiAgent: "Agente IA",
    logout: "Salir",
    disconnect: "Desconectar",
  },
  form: {
    noPermission: "No dispones de los permisos necesarios para completar este formulario.",
    submitError: "Error durante el envío.",
  },
  filter: {
    activeFilters: "Filtros activos:",
    removeAll: "Eliminar todos",
    removeFilter: "Eliminar filtro {label}",
  },
  providers: {
    rateLimitTitle: "Demasiadas Solicitudes",
    rateLimitBody: "Has actualizado la página demasiadas veces en poco tiempo. Para garantizar la estabilidad del servicio, las solicitudes frecuentes están temporalmente limitadas.",
    rateLimitHint: "Te recomendamos navegar dentro de la aplicación usando los menús y enlaces internos sin recargar toda la página.",
    waitPrefix: "Espera",
    waitSuffix: "segundos para reintentar",
    readyToRetry: "¡Listo para reintentar!",
    retrying: "Restaurando...",
    retryNow: "Reintentar Ahora",
    goBack: "Volver Atrás",
    authFailed: "Autenticación Fallida",
    cleanAndRetry: "Limpiar Sesión y Reintentar",
    csrfBlocked: "Error de validación de la sesión (CSRF bloqueado).",
    ssoExchangeFailed: "No se puede completar el intercambio del código SSO.",
    ssoNetworkError: "Error de red durante el intercambio del código SSO.",
    firebaseInitError: "Error de inicialización de Firebase Auth: {error}. Verifica que el dominio '{domain}' esté incluido entre los referrers permitidos para la clave API de Firebase.",
    firebaseClientAuthError: "No se puede autenticar la sesión de Firebase client: {error}. Verifica que el dominio '{domain}' esté incluido entre los referrers permitidos para la clave API de Firebase Auth en la consola de Google Cloud.",
  },
  modules: {
    product: {
      title: "Productos y Hardware {brand}",
      description: "Gestiona y compra sensores IoT, gateways y extensiones de hardware oficiales de {brand} para tu infraestructura.",
      searchPlaceholder: "Buscar productos por nombre, SKU o tipo...",
      tableAria: "Tabla de Productos",
      colProduct: "Producto",
      colSku: "SKU / Código",
      colCategory: "Categoría",
      colPrice: "Precio",
      colAction: "Acción",
      notAvailable: "N/D",
      buyButton: "Comprar",
      processing: "Procesando...",
      emptyState: "Ningún producto coincide con los criterios de búsqueda.",
      onlyAdminsBuy: "Solo el Owner o los Admins pueden comprar productos.",
      purchaseInit: "Inicializando la compra del producto...",
      errLoad: "No se pueden cargar los productos.",
      errConnection: "Error de conexión al recuperar los productos.",
      errCheckout: "No se puede iniciar el checkout del producto.",
      errPurchaseStart: "Error al iniciar la compra: {message}",
    },
    application: {
      title: "Aplicaciones Cloud {brand}",
      description: "Gestiona las suscripciones SaaS e inicia el onboarding para las plataformas verticales de tu organización.",
      emptyState: "Ninguna aplicación disponible en el catálogo del sistema.",
      statusSubscribed: "Suscrito",
      statusInactive: "No Activo",
      noDescription: "Aplicación vertical integrada para la gestión cloud enterprise.",
      expiryLabel: "Vencimiento:",
      modeLabel: "Modalidad:",
      priceMonthly: "{amount} € / mes",
      standardPrice: "Precio estándar",
      autoRenewMonthly: "Renovación automática mensual",
      onboardingLabel: "Onboarding de Usuario:",
      onboardingDone: "Completado",
      onboardingTodo: "Por completar",
      completeOnboarding: "Completar Onboarding",
      manageSubscription: "Gestionar Suscripción",
      subscribeNow: "Suscríbete Ahora",
      onlyAdminsSubscribe: "Solo el Owner o los Admins pueden suscribir la organización a los servicios.",
      onlyAdminsBilling: "Solo el Owner o los Admins pueden gestionar la facturación.",
      checkoutStarting: "Iniciando el checkout...",
      redirectPortal: "Redirigiendo al portal de Stripe...",
      onboardingSaving: "Registrando el onboarding...",
      onboardingSuccess: "¡Onboarding completado con éxito!",
      errSchema: "La respuesta del servidor no cumple el esquema esperado.",
      errCheckoutSession: "No se puede iniciar la sesión de checkout de Stripe.",
      errPaymentSession: "Error al crear la sesión de pago.",
      errBillingPortal: "No se puede abrir el portal de facturación.",
      errStripeConnection: "Error de conexión con Stripe.",
      errOnboardingSave: "Error al guardar el onboarding.",
      errOnboardingRegister: "No se puede registrar el onboarding.",
      errLoad: "No se pueden cargar los servicios.",
      errConnection: "Error de conexión al recuperar las aplicaciones.",
    },
    invoice: {
      title: "Registro de Facturas y Recibos",
      description: "Consulta el historial cronológico de todas las facturas recibidas por compras SaaS y de las facturas emitidas a clientes partner.",
      searchPlaceholder: "Buscar factura por ID o contraparte...",
      tableAria: "Tabla de Facturas",
      colInvoiceId: "ID Factura / Referencia",
      colFlow: "Flujo",
      colCounterparty: "Contraparte",
      colDate: "Fecha",
      colGrossAmount: "Importe Bruto",
      colStatus: "Estado",
      colActions: "Acciones",
      flowReceived: "Recibida",
      flowIssued: "Emitida",
      fromPrefix: "De:",
      toPrefix: "A:",
      partnerCustomer: "Cliente Partner",
      vatDetail: "(IVA {percent}%: {amount})",
      noPdf: "Sin PDF",
      download: "Descargar",
      filterTypeLabel: "Tipo",
      filterReceived: "Recibidas",
      filterIssued: "Emitidas",
      filterAria: "Filtro de flujo de facturas",
      filterAllFlows: "Todos los flujos",
      filterReceivedInvoices: "Facturas Recibidas",
      filterIssuedInvoices: "Facturas Emitidas",
      emptyState: "Ninguna factura coincide con los criterios establecidos.",
      errLoad: "No se puede recuperar el historial de facturas.",
      errConnection: "Error de conexión al cargar las facturas.",
    },
    subscription: {
      title: "Planes y Suscripciones",
      description: "Gestiona la suscripción mensual, los puestos de los miembros (seats) y accede a la configuración de facturación de Stripe.",
      manageOnStripe: "Gestionar en Stripe",
      pastDueTitle: "¡Suscripción Impagada!",
      pastDueBodyPrefix: "Uno o más servicios de la organización",
      pastDueBodySuffix: "están impagados. Algunas funcionalidades podrían estar suspendidas. Realiza el pago para desbloquear el acceso.",
      payNow: "Pagar Ahora",
      emptyTitle: "Ninguna suscripción activa",
      emptyBody: "Habilita una de las aplicaciones verticales o API de {brand} en el catálogo de servicios para empezar.",
      seatsLabel: "Puestos:",
      seatAssignmentTitle: "Asignación de Licencias (Seats)",
      updating: "Actualizando...",
      assigned: "Asignado",
      assign: "Asignar",
      noAdminPrivileges: "No dispones de privilegios de administrador para asignar licencias.",
      seatLimitReached: "Límite de puestos alcanzado para esta suscripción ({max}). Elimina un usuario o compra puestos nuevos.",
      emailNotFound: "Correo del usuario no encontrado.",
      seatRevoked: "Licencia revocada con éxito.",
      seatAssigned: "Licencia asignada con éxito.",
      errSeatUpdate: "No se puede actualizar la licencia.",
      errSeatUpdateDetail: "Error al actualizar la licencia: {message}",
      portalRedirect: "Redirigiendo al Stripe Customer Portal...",
      errPortalOpen: "No se puede abrir el portal de Stripe.",
      errStripeServer: "Error de conexión con el servidor de Stripe.",
      errLoadSubs: "No se puede recuperar el historial de suscripciones.",
      errLoadData: "Error al cargar los datos de suscripción.",
    },
  },
  settings: {
    totpAccountFallback: "cuenta {issuer}",
    deviceFallback: "Dispositivo",
    browserFallback: "Navegador",
    avatarAlt: "Avatar",
    subdomainPlaceholder: "tu-organizacion",
    customDomainPlaceholder: "app.tuempresa.com",
    trustedTitle: "Dispositivos de confianza (MFA)",
    trustedDesc: "En estos dispositivos, las operaciones sensibles no volverán a pedir tu contraseña/código durante 30 días. La confianza se concede al iniciar sesión, tras el código de verificación.",
    trustedEmpty: "Ningún dispositivo de confianza.",
    trustedLoading: "Cargando…",
    trustedRevoke: "Revocar",
    trustedRevoked: "Confianza del dispositivo revocada.",
    trustedRevokeFail: "No se pudo revocar el dispositivo.",
    trustedThisDevice: "Este dispositivo",
    trustedExpires: "Caduca el {date}",
  },
  dialogs: {
    support: {
      title: "Soporte Virtual {brand}",
      subtitle: "Agente IA activo",
      greeting: "¡Hola! Soy el asistente virtual de {brand} Cloud. ¿Cómo puedo ayudarte hoy con nuestros productos o servicios?",
      promptApiKey: "¿Cómo genero una clave API?",
      promptStripe: "¿Cómo funciona el onboarding de Stripe?",
      promptFls: "¿Qué es la protección FLS?",
      promptTheme: "¿Cómo cambio el idioma o el tema?",
      answerFallback: "Lo siento, no he entendido la solicitud. ¿Puedes reformular la pregunta sobre los servicios de {brand}?",
      answerApiKey: "Para generar una clave API en {brand}:\n1. Accede a la sección **API Key** desde el menú lateral.\n2. Haz clic en **Crear Clave**.\n3. Especifica los permisos para cada módulo y haz clic en Generar.\n\n*Nota: Recuerda guardar la clave de inmediato, por razones de seguridad no se mostrará una segunda vez.*",
      answerStripe: "El onboarding de Stripe te permite activar los pagos. Puedes completarlo accediendo a la sección **Payment** o desde la página del perfil de la organización, donde serás redirigido a Stripe Connect para introducir los datos fiscales de tu empresa.",
      answerFls: "{brand} adopta una seguridad a nivel de campo (Field-Level Security - FLS) y RBAC. Las políticas están definidas estáticamente en `resources.config.ts`. Solo los usuarios con rol `owner` omiten estos controles, mientras que para los demás roles las propiedades de entrada y salida se filtran automáticamente.",
      answerTheme: "Puedes cambiar el tema (claro/oscuro) haciendo clic en el icono del sol/luna en la parte inferior izquierda de la barra lateral. El idioma se gestiona según el locale configurado en la URL (it/en/es) y puede modificarse desde el panel de configuración de usuario.",
      answerGreeting: "¡Hola! ¿En qué puedo ayudarte hoy? Puedo explicarte cómo funcionan las API Keys, el onboarding de Stripe o nuestras políticas de seguridad.",
      suggestionsLabel: "Sugerencias rápidas:",
      inputPlaceholder: "Haz una pregunta sobre el soporte de {brand}...",
    },
    ai: {
      title: "Analizador de Datos IA {brand}",
      subtitle: "Agente Gemini integrado",
      greeting: "¡Hola! Soy el agente de Análisis IA de {brand}. Estoy conectado en tiempo real a tus datos de sesión y de la organización. Pídeme un análisis estructurado o información sobre los recursos activos.",
      promptOrg: "Analiza mi organización",
      promptSubs: "Muestra el estado de mis suscripciones",
      promptRole: "¿Qué permisos tiene mi rol?",
      answerFallback: "No tengo elementos suficientes para analizar esta solicitud específica. Prueba a pedirme un informe de la organización o el estado de los servicios.",
      orgNone: "Ninguna Organización Asociada",
      orgReport: "Aquí está el análisis de los datos de la organización **{org}**:\n- **Estado de Onboarding**: {onboarding}\n- **Tipo de Organización**: {type}\n- **País de Registro**: {country}\n- **Modo de Entorno**: {env}\n- **Verificación de IVA (VIES)**: {vies}\n\n*Tu rol dentro de esta organización es **{role}**, que te garantiza la visibilidad de los recursos.*",
      orgConfirmed: "🟢 Confirmado y Activo",
      orgPending: "🟡 En espera / Por confirmar",
      orgTypeStandard: "Estándar",
      orgCountryUnknown: "No Especificado",
      envTest: "🧪 Test Environment",
      envProd: "⚡ Production Live",
      viesOk: "✅ Validado con éxito",
      viesKo: "❌ No validado o no presente",
      subsEmpty: "Para la organización **{org}** no constan licencias o suscripciones activas en este momento. Puedes activar una desde la sección **Product** de nuestro portal.",
      subsFound: "He encontrado **{count}** suscripciones activas para **{org}**:",
      subItem: "{index}. **Servicio**: {service}\n   - **Estado**: {status}\n   - **Renovación Automática**: {renewal}\n   - **Fin del Periodo**: {expiry}",
      subStatusActive: "🟢 Activo",
      subStatusOther: "🟡 {status}",
      renewalOff: "❌ Desactivada",
      renewalOn: "✅ Activa",
      notAvailable: "N/D",
      roleReport: "Análisis de privilegios del usuario conectado:\n- **Rol Asignado**: `{role}`\n- **Bypass RBAC/FLS**: {bypass}\n\nTus permisos operativos te permiten visualizar y gestionar los recursos de acuerdo con el registro estático de seguridad de {brand} para la aplicación actual.",
      bypassOn: "✅ Habilitado (Bypass completo)",
      bypassOff: "❌ Deshabilitado (Sujeto a políticas)",
      answerGreeting: "¡Hola! Puedo ejecutar un análisis de tus datos en tiempo real. Pídeme un resumen de la organización o el estado de las suscripciones activas.",
      suggestionsLabel: "Sugerencias rápidas:",
      inputPlaceholder: "Pide un análisis a la IA de {brand}...",
    },
    stripeConnect: {
      errStatusFetch: "Error al recuperar el estado de la cuenta.",
      errStatusNetwork: "Error de red al verificar el estado.",
      errOnboardLink: "No se puede generar el enlace de onboarding.",
      errStripeConnection: "Error de conexión con Stripe.",
      errDashboardLink: "No se puede generar el enlace del dashboard.",
      errLinkGeneration: "Error al generar el enlace.",
      accessDeniedTitle: "Acceso Limitado",
      accessDeniedBody: "Solo el propietario de la organización (**owner**) posee las autorizaciones necesarias para configurar las cuentas bancarias, activar Stripe Connect o gestionar la configuración de cobros y payouts para los partners.",
      currentRoleLabel: "Tu rol actual:",
      roleFallback: "Miembro",
      pageTitle: "Configuración de Stripe Connect",
      pageDesc: "Habilita la recepción de pagos y gestiona el split-billing para los proyectos en los que colaboras como organización partner.",
      activeTitle: "Stripe Connect Activo",
      activeBadge: "Activo",
      accountIdLabel: "ID de Cuenta:",
      expressConsole: "Consola Express de Stripe",
      chargesLabel: "Recepción de Pagos",
      chargesEnabled: "Habilitada - Puedes cobrar split-billing",
      chargesDisabled: "Suspendida o limitada",
      payoutsLabel: "Envío de Transferencias (Payout)",
      payoutsEnabled: "Habilitado - Transferencias automáticas activas",
      payoutsDisabled: "Suspendido o en verificación",
      futureChecksTitle: "Verificaciones futuras previstas:",
      futureChecksBody: "Stripe podría solicitar información adicional en el futuro si superas determinados umbrales de cobro (p. ej. {list}).",
      incompleteTitle: "Configuración Incompleta",
      kycBadge: "KYC Requerido",
      completeSetup: "Completar Configuración",
      kycNotice: "Stripe requiere información adicional de identificación (KYC) para activar los payouts:",
      kycFallback: "Completa los pasos requeridos en el portal de Stripe Connect para poder habilitar los pagos.",
      enableTitle: "Habilita Stripe Connect para tu Organización",
      enableBody: "Conecta con seguridad una cuenta corriente o tarjeta de débito bancaria mediante Stripe Connect Express. Al habilitar Connect, tu organización podrá vender bienes de hardware, ofrecer licencias o configurar flujos de facturación recurrente split-billing con otras organizaciones partner dentro de la red {brand}.",
      safeOnboardingTitle: "Onboarding Simple y Seguro:",
      safeOnboardingBody: "Stripe Express gestiona directamente los requisitos contra el blanqueo de capitales y fiscales (KYC). {brand} no almacena de ningún modo tus datos bancarios. La comisión de la plataforma para las transacciones split de Connect está fijada en el 1%.",
      enableCta: "Activar Stripe Connect",
    },
  },
};

export const UI_STRINGS: Readonly<Record<"it" | "en" | "es", UIStrings>> = { it, en, es };

export type UILocale = keyof typeof UI_STRINGS;

/** Normalizza un locale arbitrario su quelli supportati (fallback: it). */
export function resolveUILocale(locale: string | undefined | null): UILocale {
  return locale === "en" || locale === "es" ? locale : "it";
}

/**
 * Locale con direzione di scrittura right-to-left (E3.1 DS_REFACTORING_V1_PLAN).
 * NB: i locale oggi attivi (it/en/es) sono tutti LTR — il supporto RTL è
 * PREDISPOSTO per mercati futuri (arabo, ebraico, farsi, urdu): aggiungendo
 * uno di questi locale a next-international, `dir="rtl"` su <html> e le
 * logical properties di Tailwind (ms-/me-/ps-/pe-/start-/end-…) si attivano
 * automaticamente senza altri interventi.
 */
export const RTL_LOCALES: readonly string[] = ["ar", "he", "fa", "ur"];

/**
 * Direzione di scrittura per un locale arbitrario (anche regionale, es. "ar-EG").
 * Fallback prudente: "ltr" per locale sconosciuti/assenti.
 */
export function localeDirection(locale: string | null | undefined): "ltr" | "rtl" {
  if (!locale) return "ltr";
  const base = locale.toLowerCase().split(/[-_]/)[0];
  return RTL_LOCALES.includes(base) ? "rtl" : "ltr";
}

/** Interpolazione dei segnaposto `{nome}` (es. fmtUI(s.min, { n: 3 })). */
export function fmtUI(template: string, vars: Record<string, string | number>): string {
  return template.replace(/\{(\w+)\}/g, (match, key: string) =>
    Object.prototype.hasOwnProperty.call(vars, key) ? String(vars[key]) : match
  );
}

/**
 * Hook reattivo: restituisce il dizionario UI nella lingua corrente.
 * Cambiando locale (useChangeLocale) l'intera UI del framework si aggiorna
 * senza reload. Uso: `const s = useUIStrings(); … s.common.save`.
 */
export function useUIStrings(): UIStrings {
  const locale = useCurrentLocale();
  return UI_STRINGS[resolveUILocale(locale)];
}
